# ----------------------------------------------------------------------------------------------------------------------
# Configuration/Services.yaml
# ----------------------------------------------------------------------------------------------------------------------

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Int\Intitems\:
    resource: '../Classes/*'