# ----------------------------------------------------------------------------------------------------------------------
# Configuration/Services.yaml
# ----------------------------------------------------------------------------------------------------------------------

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Int\Inthelper\:
    resource: '../Classes/*'