<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'EBT\\ExtensionBuilder\\' => array($typo3InstallDir . 'typo3conf/ext/extension_builder/Classes'),
    'Sajmon\\Test\\' => array($typo3InstallDir . 'typo3conf/ext/test/Classes'),
    'T3docs\\StoreInventory\\' => array($typo3InstallDir . 'typo3conf/ext/store_inventory/Classes'),
);
